version: '3.8'
services:
  harvester:
    build: .
    volumes:
      - .:/app
      # Pour Linux, le partage du socket X11 fonctionne directement.
      # Sous Windows/macOS, cette ligne peut être ignorée ou adaptée si vous utilisez un serveur X compatible.
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # Sous Linux, cela fonctionne si vous avez configuré `xhost` correctement.
      # Sous Windows avec VcXsrv ou sous macOS avec XQuartz, vous pourriez avoir besoin de définir DISPLAY à host.docker.internal:0 ou une adresse IP spécifique.
      - DISPLAY=${DISPLAY}
    env_file:
      - config.env
    ports:
      - "${NESTER_PORT}:${NESTER_PORT}"
    # Pour les applications GUI sous Linux, assurez-vous que le réseau est en mode 'host' pour une meilleure intégration avec X11.
    # Cette option n'est pas nécessaire/soutenue sous Windows/macOS et peut être commentée ou retirée selon votre environnement.
    #network_mode: host
